# This is a basic workflow to help you get started with Actions

name: MAIN-CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Install dependencies
      - name: install-dependencies
        run: yarn

      # Runs a single command using the runners shell
      - name: storybook
        run: yarn run build-storybook
      # Runs a single command using the runners shell
      - name: chromatic
        run: yarn run chromatic
        # with:
        #   token: ${{ secrets.REPO_TOKEN }}
        #   # 👇 Chromatic projectToken, refer to the manage page to obtain it.
        #   projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
